---
- name: Update all packages (RHEL)
  dnf:
    name: "*"
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Update all packages (Debian)
  apt:
    upgrade: dist
    update_cache: yes
    autoremove: yes
    autoclean: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install common packages (RHEL)
  dnf:
    name: "{{ common_packages_rhel }}"
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install common packages (Debian)
  apt:
    name: "{{ common_packages_debian }}"
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone
  community.general.timezone:
    name: "{{ timezone }}"

- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
  notify: Restart sshd