managed_users:
  - name: ansible
    pubkeys:
      - ansible.pub
    sudo: true
  - name: tj
    pubkeys:
      - tj-desktop.pub
    sudo: true
  - name: tj
    pubkeys:
      - tj-macbook.pub
    sudo: true
