services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - MAX_WORKERS=1
      - WEB_CONCURRENCY=1
      - BASE_URL=https://mealie.rataiczak.com
    volumes:
      - /opt/mealie/data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.entrypoints=http"
      - "traefik.http.routers.mealie.rule=Host(`mealie.rataiczak.com`)"
      - "traefik.http.routers.mealie.middlewares=traefik-https-redirect"
      - "traefik.http.routers.mealie-secure.entrypoints=https"
      - "traefik.http.routers.mealie-secure.rule=Host(`mealie.rataiczak.com`)"
      - "traefik.http.routers.mealie-secure.tls=true"
      - "traefik.http.routers.mealie-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.mealie-secure.middlewares=default-headers@docker"
      - "traefik.http.routers.mealie-secure.service=mealie"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
    networks:
      - proxy

networks:
  proxy:
    external: true
