all:
  children:
    servers:
      hosts:
        RAT-ANSIBLE-01:
          ansible_host: 10.0.20.2
          ansible_connection: local
        RAT-PROX-01:
          ansible_host: 10.0.20.3
    external:
      hosts:
        RAT-PROD-01:
          ansible_host: 10.0.60.2
